services:
  georgebot:
    image: ghcr.io/puuuchkie/georgebot:latest
    container_name: georgebot
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
